### PR TITLE
Activate static_file support on WIN32

### PR DESCRIPTION
**Pull request by epajarre**
static_file support seems to work, at least with
Microsoft Visual Studio 2017 and 2109 / C++17.
Without it the compilation fails, so activating it.

### CODE REVIEW

**Comment by The-EDev** [comment]
seems like Travis isn't running, I'm not exactly sure why..

**Review by The-EDev — CHANGES_REQUESTED** [review]
you missed a check in line 15 (and 17 for endif)

**Comment by epajarre** [comment]
> you missed a check in line 15 (and 17 for endif) in `http_response.h`

Sorry for that, It DID compile even without that change, I guess the declaration is included through the other headers, but of course better to be explicit.

 Eero

**Comment by epajarre** [comment]
Sorry for the delay, I am just learning the Github workflow....

**Review by The-EDev — APPROVED** [review]

**Pull request merged**
